int ft_itoa(char *str);
int ft_isalnum(int c);
char *ft_strstr(char *s1, char *s2);
int ft_isprint(int c);
char *ft_strchr(const char *str, int c);
size_t ft_strlen(const char *s);
void *ft_memset(void *str, int c, size_t n);
int ft_atoi(const char *str);
int ft_toupper(int c);
int ft_tolower(int c);
int ft_isalpha(int c);
char *ft_strrchr(const char *s, int c);
int ft_isdigit(int c);
int ft_isalnum(int c);
int ft_isascii(int c);
void ft_bzero(void *s, size_t n);
size_t ft_strlen(const char *s);
