extern char *ft_itoa(int n);
int ft_atoi(char *str);
int ft_isalnum(int c);
int ft_isalpha(int c);
int ft_isascii(int c);
int ft_isdigit(int c);
int ft_isprint(int c);
char *ft_strstr(char *s1, char *s2);
int ft_toupper(int c);
int ft_tolower(int c);